### ISSUE TITLE
SADeprecationWarning: The Binary type has been renamed to LargeBinary.

### ISSUE THREAD

**Issue by Harosgr** [dmsimard/ara#110]
There is some kind of issue with ara using sqlalchemy.

When I try to do even the simplest thing, like "ara help". I get:

```
/home/nafpliot/workspace/venv/lib/python2.6/site-packages/sqlalchemy/sql/type_api.py:1258: SADeprecationWarning: The Binary type has been renamed to LargeBinary.
  return typeobj(*arg, **kw)
Traceback (most recent call last):
  File "/home/nafpliot/workspace/venv/bin/ara", line 7, in <module>
    from ara.shell import main
  File "/home/nafpliot/workspace/venv/lib/python2.6/site-packages/ara/__init__.py", line 16, in <module>
    from ara.webapp import create_app
  File "/home/nafpliot/workspace/venv/lib/python2.6/site-packages/ara/webapp.py", line 26, in <module>
    import ara.config
  File "/home/nafpliot/workspace/venv/lib/python2.6/site-packages/ara/config.py", line 21, in <module>
    DEFAULT_DATABASE = 'sqlite:///{}'.format(DEFAULT_DATABASE_PATH)
ValueError: zero length field name in format
```

**Comment by dmsimard** [comment]
Hi @Harosgr 

I'm unable to reproduce this right now, can you please let me know how you installed ara ? Also, can you provide the output of "pip freeze" ?

Do you have a way to test this under python 2.7 ? I have not tried ARA (or Ansible) on anything older than 2.7.

**Comment by Harosgr** [comment]
Hello @dmsimard 

I installed ARA with PIP. I just configured the callback directory in ansible.cfg and let the other options default.

my pip freeze:

```
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
ansible==2.1.2.0
ara==0.9.2
argparse==1.4.0
cffi==1.8.3
click==6.6
cliff==2.2.0
cmd2==0.6.9
cryptography==1.5.2
debtcollector==1.9.0
decorator==4.0.10
ecdsa==0.13
enum34==1.1.6
Flask==0.11.1
Flask-Script==2.0.5
Flask-SQLAlchemy==2.1
Frozen-Flask==0.13
funcsigs==1.0.2
idna==2.1
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
ordereddict==1.1
paramiko==2.0.2
pbr==1.10.0
prettytable==0.7.2
pyasn1==0.1.9
pycparser==2.16
pycrypto==2.6.1
Pygments==2.1.3
PyMySQL==0.7.9
pyparsing==2.1.10
PyYAML==3.12
six==1.10.0
SQLAlchemy==1.1.3
stevedore==1.18.0
unicodecsv==0.14.1
Werkzeug==0.11.11
wrapt==1.10.8
```
I'll try to test it also under python 2.7 and let you know.

**Comment by dmsimard** [comment]
That pip freeze looks good to me, pretty much the same thing as I have. Let me know what happens when testing under 2.7.

Thanks.

**Comment by Harosgr** [comment]
hey @dmsimard 

python 2.7 seems to fix the problem. Thanks. =)

**Comment by dmsimard** [comment]
@Harosgr great! I'll make note of this somewhere in the documentation soon, leaving this opened in the meantime. Unfortunately I don't plan on trying to support anything older than 2.7, especially as Ansible is trying hard to push towards python 3.
