### ISSUE TITLE
Stack trace when trying to get stats for a playbook that didn't finish (?)

### ISSUE THREAD

**Issue by dmsimard** [dmsimard/ara#65]
Traceback (most recent call last):
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
            response = self.full_dispatch_request()
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
            rv = self.handle_user_exception(e)
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
            reraise(exc_type, exc_value, tb)
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
            rv = self.dispatch_request()
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
            return self.view_functions[rule.endpoint](**req.view_args)
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/ara/views/host.py", line 23, in show_host
            return render_template('host.html', host=host)
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
            context, ctx.app)
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
            rv = template.render(context)
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
            return self.environment.handle_exception(exc_info, True)
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
            reraise(exc_type, exc_value, tb)
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/ara/templates/host.html", line 1, in top-level template code
            {% extends "layout.html" %}
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/ara/templates/layout.html", line 28, in top-level template code
            {% block content %}
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/ara/templates/host.html", line 22, in block "content"
            {% set stats = host.stats.filter_by(playbook_id=playbook.id).one() %}
          File "/home/dmsimard/dev/ara/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2699, in one
            raise orm_exc.NoResultFound("No row was found for one()")
        NoResultFound: No row was found for one()

**Comment by dmsimard** [comment]
[ansible.sqlite.zip](https://github.com/dmsimard/ara/files/284851/ansible.sqlite.zip)

**Comment by dmsimard** [comment]
This can be reproduced using the attached database and going in host and clicking any host. Also reproduced from the summary table.

**Comment by dmsimard** [comment]
Sort of related to https://github.com/dmsimard/ara/issues/57 .
