### ISSUE TITLE
Decorator stack trace when running callback through playbook

### ISSUE THREAD

**Issue by dmsimard** [dmsimard/ara#97]
Note sure what's this about yet. Documenting before I forget or lose it.

    [root@n22 kolla]# ansible-playbook -vv test.yml
    Using /etc/ansible/ansible.cfg as config file
     [WARNING]: Host file not found: /etc/ansible/hosts
    
     [WARNING]: provided hosts list is empty, only localhost is available
    
    ERROR! Unexpected Exception: 'module' object has no attribute 'decorate'
    to see the full traceback, use -vvv
    [root@n22 kolla]# ansible-playbook -vvvv test.yml
    Using /etc/ansible/ansible.cfg as config file
     [WARNING]: Host file not found: /etc/ansible/hosts
    
     [WARNING]: provided hosts list is empty, only localhost is available
    
    Loaded callback default of type stdout, v2.0
    ERROR! Unexpected Exception: 'module' object has no attribute 'decorate'
    the full traceback was:
    
    Traceback (most recent call last):
      File "/usr/bin/ansible-playbook", line 92, in <module>
        exit_code = cli.run()
      File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
        results = pbex.run()
      File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 80, in run
        self._tqm.load_callbacks()
      File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 164, in load_callbacks
        for callback_plugin in callback_loader.all(class_only=True):
      File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 368, in all
        self._module_cache[path] = self._load_module_source(name, path)
      File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 319, in _load_module_source
        module = imp.load_source(name, path, module_file)
      File "/usr/lib/python2.7/site-packages/ara/callback/log_ara.py", line 59, in <module>
        class CallbackModule(CallbackBase):
      File "/usr/lib/python2.7/site-packages/ara/callback/log_ara.py", line 46, in __new__
        attrs[k] = commit_after(v)
      File "/usr/lib/python2.7/site-packages/ara/callback/log_ara.py", line 42, in commit_after
        return decorator.decorate(func, _commit_after)
    AttributeError: 'module' object has no attribute 'decorate'
    [root@n22 kolla]# ansible --version
    ansible 2.1.0.0
      config file = /etc/ansible/ansible.cfg
      configured module search path = Default w/o overrides
    [root@n22 kolla]# ara --version
    ara 0.8.0
    [root@n22 kolla]# cat /etc/ansible/ansible.cfg
    [defaults]
    callback_plugins = /usr/lib/python2.7/site-packages/ara/callback:$VIRTUAL_ENV/lib/python2.7/site-packages/ara/callback:/usr/local/lib/python2.7/dist-packages/ara/callback
    [root@n22 kolla]# cat test
    test-requirements.txt  tests/                 test.yml
    [root@n22 kolla]# cat test.yml
    - name: Test playbook
      hosts: localhost
      become: yes
      become_user: root
      gather_facts: yes
      tasks:
        - name: Really debug thing
          debug:
            msg: "Really debug thing"
    [root@n22 kolla]# pip freeze
    You are using pip version 7.1.0, however version 8.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    ansible==2.1.0.0
    appdirs==1.4.0
    ara==0.8.0
    Babel==2.3.4
    backports.ssl-match-hostname==3.5.0.1
    beautifulsoup4==4.4.1
    cffi==1.6.0
    chardet==2.2.1
    click==6.6
    cliff==2.0.0
    cmd2==0.6.8
    configobj==4.7.2
    cryptography==1.3.4
    debtcollector==1.4.0
    decorator==3.4.0
    docker-py==1.7.2
    enum34==1.1.6
    Flask==0.11
    Flask-Script==2.0.5
    Flask-SQLAlchemy==2.1
    Frozen-Flask==0.12
    funcsigs==1.0.2
    functools32==3.2.3.post2
    gitdb==0.6.4
    GitPython==2.0.5
    graphviz==0.4.10
    idna==2.1
    iniparse==0.4
    ipaddress==1.0.16
    IPy==0.75
    iso8601==0.1.11
    itsdangerous==0.24
    Jinja2==2.8
    jsonpatch==1.14
    jsonpointer==1.10
    jsonschema==2.5.1
    keystoneauth1==2.8.0
    kitchen==1.1.1
    kolla==2.0.0.0rc2.dev589
    MarkupSafe==0.23
    monotonic==1.1
    msgpack-python==0.4.7
    netaddr==0.7.18
    netifaces==0.10.4
    openstacksdk==0.8.6
    os-client-config==1.18.0
    oslo.config==3.10.0
    oslo.i18n==3.6.0
    oslo.serialization==2.7.0
    oslo.utils==3.11.0
    paramiko==2.0.0
    pbr==1.10.0
    perf==0.1
    policycoreutils-default-encoding==0.1
    positional==1.1.0
    prettytable==0.7.2
    pyasn1==0.1.9
    pycparser==2.14
    pycrypto==2.6.1
    pycurl==7.19.0
    pygobject==3.14.0
    pygpgme==0.3
    pyliblzma==0.5.3
    PyMySQL==0.7.4
    pyparsing==2.1.4
    python-cinderclient==1.8.0
    python-glanceclient==2.0.0
    python-keystoneclient==3.1.0
    python-neutronclient==4.2.0
    python-novaclient==4.0.0
    python-openstackclient==2.5.0
    pytz==2016.4
    pyudev==0.15
    pyxattr==0.5.1
    PyYAML==3.11
    requests==2.10.0
    requestsexceptions==1.1.3
    seobject==0.1
    sepolicy==1.1
    simplejson==3.8.2
    six==1.10.0
    slip==0.4.0
    slip.dbus==0.4.0
    smmap==0.9.0
    SQLAlchemy==1.0.13
    stevedore==1.14.0
    unicodecsv==0.14.1
    urlgrabber==3.10
    warlock==1.2.0
    websocket-client==0.37.0
    Werkzeug==0.11.10
    wrapt==1.10.8
    yum-metadata-parser==1.1.4

**Comment by dmsimard** [comment]
Fixed when upgrading decorator and using the same one as my local venv:

    Collecting decorator==4.0.9
      Downloading decorator-4.0.9-py2.py3-none-any.whl
    Installing collected packages: decorator
      Found existing installation: decorator 3.4.0
        Uninstalling decorator-3.4.0:
          Successfully uninstalled decorator-3.4.0
    Successfully installed decorator-4.0.9


I suspect decorator 3.4.0 was picked due to openstack global reqs in https://github.com/openstack/requirements/blob/4d9ace870ddd06621c60b5535265aa4857e498ff/global-requirements.txt#L26

We ought to pick the version that we need and enforce it.

**Comment by dmsimard** [comment]
Fixed in https://github.com/dmsimard/ara/commit/f141cdfb9fc041c707e719710bd708997a733cf3
